### ISSUE TITLE
Add a response for BLT file format questions

### ISSUE THREAD

**Issue by Oaphi** [samliew/se-electionbot#145]
When the election ends, a ballot file becomes available - we should add responses to what it is and how to find it (even if in a form of an annotated link to [OpaVote's website](https://www.opavote.com/help/overview#blt-file-format)). Mostly a note to not forget to implement it until the end of the election phase (to have some time in advance - till October 22nd).

**Comment by samliew** [comment]
I don't feel that it's necessary, but you can add a response if you'd like.
