### ISSUE TITLE
When election has ended, do not scrape withdrawn candidates from chat transcript on startup

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#150]
Because bot could be in the development chat room

![Screenshot_2021-10-27_111006](https://user-images.githubusercontent.com/845988/138995037-ecc00809-de30-4be0-b34d-99e40cf04dcc.png)

**Comment by Oaphi** [comment]
Found the issue and fixed in 4b53fa1 and when switching nominees list to `Map<userId, Nominee>`, closing as obsolete
