### ISSUE TITLE
Markdown to HTML conversion incorrect strikethrough

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#164]
The markdown to HTML conversion makes this table header a strikethrough when displayed in the dashboard

![Screenshot_2022-04-16_190446](https://user-images.githubusercontent.com/845988/163672536-685403a1-57f3-45db-b11e-5fbefb941d74.png)

**Comment by Oaphi** [comment]
Opted for [Markdown-it](https://www.npmjs.com/package/markdown-it) for table rendering (we might want to migrate the whole thing to it), WIP now, but looks good, just needs a minor top-margin adjustment before I can push it live:

![ice_screenshot_20220417-030909](https://user-images.githubusercontent.com/34833340/163694986-b9dab3cf-8cc0-4d3f-afe6-fe41d59b2046.png)
