### ISSUE TITLE
Nomination period extension before cancellation

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#182]
If the election is to be extended for a week due to insufficient candidates, it should not say cancelled.

![Screenshot_2022-05-31_190525](https://user-images.githubusercontent.com/845988/171167625-2c729c74-e6e9-4144-869e-5dd595c9c6b1.png)

https://chat.stackexchange.com/transcript/message/61237556#61237556

**Comment by Oaphi** [comment]
Nearly wrapped up with improving this, settled on the following wording for now:

https://chat.stackexchange.com/transcript/message/61260441#61260441

Tests indicate the logic should be sound, will be ready to push soon after a bit of cleanup!
