### ISSUE TITLE
get maintainerChatIds should default to empty array if config var not set

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#184]
> SERVER - failed to render home route: TypeError: Cannot read properties of undefined (reading 'stackexchange.com')
> at BotConfig.get maintainerChatIds [as maintainerChatIds] (file:///app/dist/bot/config.js:115:22)

Also reduce dependency on this in case it is not set.

**Comment by Oaphi** [comment]
d'oh! I have nothing to add :)

**Comment by Oaphi** [comment]
Fixed in 1573f2b
