### ISSUE TITLE
Pro-tem: which mods are running/have not nominated yet

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#190]
If it's a graduation election, the appointed mods have to run if they wish to continue being a mod.

We could add a new command to ask which ones are running for, or have not submitted their nomination (yet - if nomination phase, or stepping down if past the nomination phase).

![Screenshot_2022-06-06_110600](https://user-images.githubusercontent.com/845988/172092254-29cc6bcf-a193-4edd-a257-af1127536a9f.png)

https://chat.stackexchange.com/transcript/message/61292331#61292331

**Comment by Oaphi** [comment]
Builder and guard added. Initial use cases:

- https://chat.stackexchange.com/transcript/message/61315673#61315673
- https://chat.stackexchange.com/transcript/message/61315665#61315665
- https://chat.stackexchange.com/transcript/message/61315473#61315473
