### ISSUE TITLE
On Tezos election, the bot does not announce new nominees

### ISSUE THREAD

**Issue by Oaphi** [samliew/se-electionbot#203]
It is now the second time that the bot hasn't announced new nominees as they arrive:
https://chat.stackexchange.com/rooms/137876/2022-tezos-stack-exchange-moderator-election-chat

Since the periodic announcements show the number of nominees correctly, the scraping is not affected, however, we, for some reason, do not hit `announceNewNominees`.

**Comment by Oaphi** [comment]
The real issue, however, is that the `Election` class is designed to lose track of history previous history every 2 rescrapes, which is helpful during normal operation. When something goes wrong (f.e. from SE's side), the state of announcements can't be recovered due to this. I am switching to storing announced nominees / winners separately instead of relying on checking `prev.nominees` as this information is really something that we should bookkeep for the duration of the election.

**Comment by Oaphi** [comment]
That said, bookkeeping should happen in the `ScheduledAnnouncement` class as adding such bookkeeping to the `Election` class explicitly violates SRP. Honestly, we should split the former class into 2: the one that schedules and the one that announces as, come to think of it, we violate SRP in it too. Doing this also has the benefit of simplifying bookkeeping of announcements.

**Comment by samliew** [comment]
Hmm, why not have a persistent db across all instances to keep track of historical elections instead?

**Comment by Oaphi** [comment]
Yeah, it's just about tracking announcements via the `Announcer` class as opposed to trying to determine whether we have announced something by comparing previous election state to the current election state. My reasoning is that this approach will reduce interdependency of the classes (as `Election` will be free from tracking this) + bring us closer to addressing #62 too (as we can also persist nominees and winners to avoid the need to scrape the election when it is over).
