### ISSUE TITLE
Do not show dev-only commands to mods; remove or split to separate dev menu

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#66]
Dev-only commands should not be shown to mods when using `@ElectionBot commands`, otherwise they will get confused when a command doesn't get a response.

![Screenshot_2021-08-21_160813](https://user-images.githubusercontent.com/845988/130315804-71e52c97-9c4c-4170-b798-4f8330afa602.png)

I've already [removed](https://github.com/samliew/se-electionbot/commit/8eea731dfd04da2420c177ed0bfdd2a9092bcdbd#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L540) the keyword `help` from displaying the mod-only menu, as I intend this to display the user help menu.

**Comment by Oaphi** [comment]
Agreed, @samliew  - I just didn't have enough time to spare to connect those to the help menu. I had an idea in mind to simply enrich the `CommandManager`'s `help` method to filter commands by access level (i.e. not show those that are not available)

**Comment by samliew** [comment]
No, anyone should be able to trigger the bot to show example topics it can help with. Privileged mention-only commands are to be shown separately, and some mention only triggers should not be shown at all especially when a live election is going on.

**Comment by Oaphi** [comment]
Oh, I think we misunderstood each other a little bit here :) I was referring to "dev-only commands should not be shown to mods" - since we now have privilege levels, the `help` method (not the command that you disambiguated) could show only those commands that are available to the user as you mentioned.

**Comment by samliew** [comment]
Maybe dev-only commands shown only when election is not active then

**Comment by Oaphi** [comment]
Hmm... can you clarify a little who would this affect? Do you mean that we can show dev-only commands to mods as well when there is no election or something?

**Comment by samliew** [comment]
Should devs or mods who are also a dev use the `command` trigger during an election, the bot should only show the mod-only commands. Devs should still be able to use any privileged commands, and mods should still be able to use mod-only commands at any time.

Should a other users use the `command` trigger at any time, don't do/show anything. (Currently the case)

Outside of an election, you can display all dev commands if a dev uses `commands`, but IMO it's not necessary. Mods will still get their mod-only commands displayed to them.

**Comment by Oaphi** [comment]
Ah, then that is mostly what I am proposing to do as well :) Apart from not showing dev commands to devs during elections, of course, but I now understand what you meant - looks quite plausible to do. The rest is easily achievable with the current setup, and I am about to make a PR later today (or, possibly, tomorrow) that makes it so.

**Comment by samliew** [comment]
I think the "don't show dev commands during active election" bit is nice to have but not entirely necessary.
