### ISSUE TITLE
Consider storing a separate list of adminIds and devIds for different chat domains

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#70]
Currently envars `ADMIN_IDS` and `DEV_IDS` are for our accounts on Chat.SO.

Our ids are different on Chat.SE and Chat.Meta.SE, so it makes sense to check against a different set when the bot is in these domains.

However unlikely, we do not know if a fourth chat server may be spun up in the future, so consideration may need to be made for that as well.

Also need to consider support should the bot spawn child processes for different chat servers/rooms (#61)

E.g.: my Chat.SO id is [584192](https://chat.stackoverflow.com/users/584192/samuel-liew), while on Chat.SE is [86504](https://chat.stackexchange.com/users/86504/samuel-liew)

I've made you an RO of the network test room: https://chat.stackexchange.com/rooms/info/92073/?tab=access

**Comment by Oaphi** [comment]
Hmm... I thought about this for a little while, and I think I *might* have a generic solution for that. We could expand on the ChatExchange package to attempt to scrape user's "network profile" page as well to extract user ids for other chat servers. This could work like this:

1. The chat-server user page is scraped -> we get access to the user profile link: https://stackoverflow.com/users/11407695
2. The user profile page is then scraped -> we get access to the network profile link: https://stackexchange.com/users/15810379
3. From 2, a <site, id> map is parsed
4. The current chat host is used to fetch the correct id from the map obtained in step 3
5. Processing is resumed as usual

On the note of point 3, I've confirmed that the mapping is consistent: Meta Stack Exchange account id gets mapped to the chat.meta.stackexchange.com server id (mine is 786798, for example).

What do you think? To avoid performance bottlenecks, we could limit this extra scraping to only handle what's absolutely needed

**Comment by samliew** [comment]
I might already have a solution (or reverse solution) made for this using the API. See the part about getting the user's siteId from chatId when the trigger "what is my candidate score" is used on Chat.SE

**Comment by Oaphi** [comment]
Ah, yes, true, this is easier to get via the API, forgot about that. I'll keep the idea as a fallback plan in mind then
