### ISSUE TITLE
Bot instance should only listen to events for the room it is connected to

### ISSUE THREAD

**Issue by samliew** [samliew/se-electionbot#73]
Currently, when bot is in multiple rooms, a triggering message event in any of the rooms will cause the bot to respond in the room that it's listening to.

We must be careful about this because the bot can't leave rooms by itself, so if we are testing in another room using a local instance, the main instance will still get those events and causing it to also respond in the election chat room (or all instances).

We need to get the event's room Id, and ignore it if it's not from the same room that it's listening/connected to.

A temporary fix would be to kick bot from all except one room. However this will raise automatic flags for privileged users (mods) in other rooms. Another option would be to login as that account and then leave the rooms.

**Comment by Oaphi** [comment]
Seems like the room id is readily available in the `msg` parameter of the `message` event listener callback, so this should not be a problem (unless I am missing something). Re: kick - oh, maybe we would want to avoid that, folks from MSE got really angry with a chat room that was doing exactly that with their bots...

**Comment by samliew** [comment]
Commit 0b95950 seems to break something, I recalled doing something like this before but didn't manage to solve it.

**Comment by Oaphi** [comment]
You know, I just tested the latest version of the bot on two chat servers, and the issue is not reproducible. Does it only happen if the rooms are on the same server?

**Comment by samliew** [comment]
Yup other rooms on the same server as the one the bot is connected to.

**Comment by Oaphi** [comment]
Just tested on one chat server with `joinRoomCommand` - everything works fine in the newest version of ChatExchange, no accidental command execution.
