### ISSUE TITLE
getSiteUserIdFromChatStackExchangeId network user id lookup is broken

### ISSUE THREAD

**Issue by Oaphi** [samliew/se-electionbot#83]
`getSiteUserIdFromChatStackExchangeId` function relies on scraping the profile page of the user to get the network user id in case it did not get one from the "linked site". Unfortunately, it is now broken (as indicated by the failing CI) - I highly suspect this is due to the recent change to profile pages that SE made (see [MSE post](https://meta.stackexchange.com/q/369276/786798)).

I already know how to fix it and will make a PR a bit later, but opening the issue for documentation purposes 😇

**Comment by samliew** [comment]
Oho! I didn't realise it was due to the UI change

**Comment by Oaphi** [comment]
Yeah, this is where network user URL lives now:

![navigation](https://user-images.githubusercontent.com/34833340/131813329-8d80800f-5877-490d-9f0a-30c57dae944a.png)

The one we used to look up (`.js-user-header a`) now results in picking up the first user account (in Marc's case - on SO) and using this id instead resulting in a completely unrelated user's associated accounts being returned 😥

**Comment by samliew** [comment]
If there's a breaking issue and not too big a change, just push to master first next time, and then I'll ask/comment if I don't understand what a commit was made for.

**Comment by Oaphi** [comment]
Sure, agreed - I created the issue as soon as noticed CI is failing for future reference - some extra context never hurts
